# Copyright (c) 2024-2025 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: landingpage-route
  namespace: {{ .Values.config.namespacePrefix }}horizon
  labels:
    gateway: gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway
      namespace: {{ .Values.config.namespacePrefix }}gke-gateway
      sectionName: https
  hostnames:
    - {{ .Values.config.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: {{ .Values.config.domain }}
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: X-Frame-Options
                value: SAMEORIGIN
              - name: Cache-Control
                value: public, max-age=14400
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: X-Content-Type-Options
                value: nosniff
              - name: Content-Security-Policy
                value: >
                  default-src 'self' 'unsafe-eval' 'unsafe-inline' *.accenture.com *.esrlabs.com;
                  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.cloudfront.net;
                  font-src 'self' data:;
                  script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://*.google-analytics.com https://*.cloudfront.net https://www.googletagmanager.com;
                  img-src 'self' *.accenture.com *.esrlabs.com data:;
                  connect-src 'self' *.accenture.com *.esrlabs.com https://*.google-analytics.com;
                  style-src 'self' 'unsafe-inline' https://unpkg.com;
                  upgrade-insecure-requests;
                  block-all-mixed-content;
      backendRefs:
        - name: {{ .Values.config.namespacePrefix }}landingpage
          port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: landingpage-healthcheck
  namespace: {{ .Values.config.namespacePrefix }}horizon
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.config.namespacePrefix }}landingpage
---
# Allow Landing Page ingress from Gateway
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-landingpage-ingress-from-gateway
  namespace: {{ .Values.config.namespacePrefix }}horizon
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: landingpage
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80     # HTTP UI

{{- end }}
